name: Move Issue to Project
on:
  issues:
    types: [opened]

jobs:
  move_issue_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Move Issue to Project
        run: |
          # Extract the necessary information
          ISSUE_NUMBER=${{ github.event.issue.number }}
          PROJECT_ID=1   # Replace with your actual project ID
          COLUMN_ID='Todo'  # Replace with your actual column ID

          # Move the issue to the project and column using the GitHub REST API
          curl -X POST \
            -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/projects/columns/cards/$ISSUE_NUMBER/moves \
            -d "{ \"position\": \"top\", \"column_id\": $COLUMN_ID }"
