name: Print Issue Status
on:
  issues:
    types:
      - closed

jobs:
  print_issue_status:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Get Issue URL
        id: get_url
        run: |
          ISSUE_URL=$(echo "${{ github.event.issue.html_url }}")
          echo $ISSUE_URL

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Run hello
        run: |
          result=$(node -e "const hello = require('./hello'); console.log(hello());")
          echo "Result: $result"
